(function(g){var window=this;var $wa=function(a,b){return g.Lb(a,b)},X5=function(a,b,c){a.A.set(b,c)},Y5=function(a){X5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.C)()).toString(36));
return a},Z5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.fn(a.A,b,c)},axa=function(a,b){var c=[];
g.mk(b,function(d){try{var e=g.fo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.eo(e)&&c.push(d)},a);
return c},bxa=function(a,b){var c=axa(a,b);
(0,g.y)(c,function(d){g.fo.prototype.remove.call(this,d)},a)},cxa=function(a){if(a.Lc){if(a.Lc.locationOverrideToken)return{locationOverrideToken:a.Lc.locationOverrideToken};
if(null!=a.Lc.latitudeE7&&null!=a.Lc.longitudeE7)return{latitudeE7:a.Lc.latitudeE7,longitudeE7:a.Lc.longitudeE7}}return null},dxa=function(a,b){g.bb(a,b)||a.push(b)},$5=function(a){var b=0,c;
for(c in a)b++;return b},exa=function(a,b){var c=b instanceof g.yc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},a6=function(){},fxa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gxa=function(a){if(a.Ld&&"function"==typeof a.Ld)return a.Ld();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Hb(a)},hxa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.ze&&"function"==typeof a.ze)var c=a.ze();else if(a.Ld&&"function"==typeof a.Ld)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Ib(a);d=gxa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},ixa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&(e.u=d);return e},b6=function(a,b){g.Ro[a]=!0;
var c=g.Po();c&&c.publish.apply(c,arguments);g.Ro[a]=!1},c6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Rm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jxa(this,a.capabilities||""),kxa(this,a.experiments||""))},jxa=function(a,b){a.capabilities.clear();
(0,g.ze)(b.split(","),g.Qa($wa,lxa)).forEach(function(c){a.capabilities.add(c)})},kxa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},d6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},e6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},mxa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nxa=function(a){return new d6(a)},oxa=function(a){return Array.isArray(a)?(0,g.Hc)(a,nxa):[]},f6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},g6=function(a){return Array.isArray(a)?"["+(0,g.Hc)(a,f6).join(",")+"]":"null"},h6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},pxa=function(a){return(0,g.Hc)(a,function(b){return{key:b.id,
name:b.name}})},i6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},j6=function(a,b){return g.Za(a,function(c){return e6(c,b)})},qxa=function(){var a=(0,g.ts)();
a&&bxa(a,a.o.jg(!0))},k6=function(){var a=g.ws("yt-remote-connected-devices")||[];
g.ub(a);return a},rxa=function(a){if(g.db(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Hc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},sxa=function(a){g.vs("yt-remote-connected-devices",a,86400)},m6=function(){if(l6)return l6;
var a=g.ws("yt-remote-device-id");a||(a=h6(),g.vs("yt-remote-device-id",a,31536E3));for(var b=k6(),c=1,d=a;g.bb(b,d);)c++,d=a+"#"+c;return l6=d},n6=function(){var a=k6(),b=m6();
g.bb(a,b);g.ys()&&g.wb(a,b);a=rxa(a);if(g.db(a))try{g.Gq("remote_sid")}catch(c){}else try{g.Eq("remote_sid",a.join(","),-1)}catch(c){}},txa=function(){return g.ws("yt-remote-session-browser-channel")},uxa=function(){return g.ws("yt-remote-local-screens")||[]},vxa=function(){g.vs("yt-remote-lounge-token-expiration",!0,86400)},wxa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Hc)(uxa(),function(d){return d.loungeToken}),c=(0,g.Hc)(a,function(d){return d.loungeToken});
(0,g.yi)(c,function(d){return!g.bb(b,d)})&&vxa();
g.vs("yt-remote-local-screens",a,31536E3)},xxa=function(a,b){g.vs("yt-remote-session-browser-channel",a);
g.vs("yt-remote-session-screen-id",b);var c=k6(),d=m6();g.bb(c,d)||c.push(d);sxa(c);n6()},o6=function(a){a||(g.xs("yt-remote-session-screen-id"),g.xs("yt-remote-session-video-id"));
n6();a=k6();g.gb(a,m6());sxa(a)},yxa=function(){if(!p6){var a=g.po();
a&&(p6=new g.Zn(a))}return p6?!!p6.get("yt-remote-use-staging-server"):!1},zxa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Axa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},q6=function(a){a.length?Bxa(a.shift(),function(){q6(a)}):r6()},Cxa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Bxa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},r6=function(){var a=Axa();
a&&a(!1,"No cast extension found")},Exa=function(){if(Dxa){var a=2,b=Axa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Bxa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",r6,c)}},Fxa=function(){Exa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);q6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},s6=function(a,b,c){g.z.call(this);
this.D=null!=c?(0,g.x)(a,c):a;this.Fd=b;this.C=(0,g.x)(this.zF,this);this.o=!1;this.u=0;this.A=this.Ia=null;this.B=[]},t6=function(a,b,c){g.z.call(this);
this.B=null!=c?a.bind(c):a;this.Fd=b;this.A=null;this.o=!1;this.u=0;this.Ia=null},u6=function(a){a.Ia=g.Yf(function(){a.Ia=null;
a.o&&!a.u&&(a.o=!1,u6(a))},a.Fd);
var b=a.A;a.A=null;a.B.apply(null,b)},v6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return fxa(a)},w6=function(){},x6=function(){},Gxa=function(){},Ixa=function(a){return(a=Hxa(a))?new ActiveXObject(a):new XMLHttpRequest},Hxa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},y6=function(a,b,c,d){this.o=a;
this.A=b;this.H=c;this.G=d||1;this.C=45E3;this.B=new g.w1(this);this.u=new g.Xf;this.u.setInterval(250)},Kxa=function(a,b,c){a.Yk=1;
a.dh=Y5(b.clone());a.mj=c;a.D=!0;Jxa(a,null)},z6=function(a,b,c,d,e){a.Yk=1;
a.dh=Y5(b.clone());a.mj=null;a.D=c;e&&(a.jC=!1);Jxa(a,d)},Jxa=function(a,b){a.Sk=(0,g.C)();
A6(a);a.Zh=a.dh.clone();Z5(a.Zh,"t",a.G);a.fn=0;a.Pc=a.o.Fr(a.o.Vm()?b:null);0<a.Cs&&(a.Yp=new t6((0,g.x)(a.iD,a,a.Pc),a.Cs));a.B.na(a.Pc,"readystatechange",a.UN);var c=a.Ji?g.Rb(a.Ji):{};a.mj?(a.Iq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Pc.send(a.Zh,a.Iq,a.mj,c)):(a.Iq="GET",a.jC&&!g.oe&&(c.Connection="close"),a.Pc.send(a.Zh,a.Iq,null,c));a.o.mf(1)},Nxa=function(a,b,c){for(var d=!0;!a.ti&&a.fn<c.length;){var e=Lxa(a,c);
if(e==B6){4==b&&(a.wh=4,C6(15),d=!1);break}else if(e==Mxa){a.wh=4;C6(16);d=!1;break}else D6(a,e)}4==b&&0==c.length&&(a.wh=1,C6(17),d=!1);a.sf=a.sf&&d;d||(E6(a),F6(a))},Lxa=function(a,b){var c=a.fn,d=b.indexOf("\n",c);
if(-1==d)return B6;c=Number(b.substring(c,d));if(isNaN(c))return Mxa;d+=1;if(d+c>b.length)return B6;var e=b.substr(d,c);a.fn=d+c;return e},Pxa=function(a,b){a.Sk=(0,g.C)();
A6(a);var c=b?window.location.hostname:"";a.Zh=a.dh.clone();X5(a.Zh,"DOMAIN",c);X5(a.Zh,"t",a.G);try{a.wf=new ActiveXObject("htmlfile")}catch(n){E6(a);a.wh=7;C6(22);F6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in G6)h=G6[l];else if(l in Oxa)h=G6[l]=Oxa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
G6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.$c(g.bc("b/12014412"),d+"</body></html>");a.wf.open();a.wf.write(g.Vc(c));a.wf.close();a.wf.parentWindow.m=(0,g.x)(a.lN,a);a.wf.parentWindow.d=(0,g.x)(a.rB,a,!0);a.wf.parentWindow.rpcClose=(0,g.x)(a.rB,a,!1);c=a.wf.createElement("DIV");a.wf.parentWindow.document.body.appendChild(c);d=g.Bc(a.Zh.toString());d=g.hd(g.zc(d));d=g.$c(g.bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ad(c,d);a.o.mf(1)},A6=function(a){a.Av=(0,g.C)()+a.C;
Qxa(a,a.C)},Qxa=function(a,b){if(null!=a.kl)throw Error("WatchDog timer not null");
a.kl=H6((0,g.x)(a.tN,a),b)},I6=function(a){a.kl&&(g.v.clearTimeout(a.kl),a.kl=null)},F6=function(a){a.o.dy()||a.ti||a.o.wo(a)},E6=function(a){I6(a);
g.Le(a.Yp);a.Yp=null;a.u.stop();g.Lra(a.B);if(a.Pc){var b=a.Pc;a.Pc=null;b.abort();b.dispose()}a.wf&&(a.wf=null)},D6=function(a,b){try{a.o.jB(a,b),a.o.mf(4)}catch(c){}},Sxa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Rxa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){Sxa(a,b,c,d,f)},f)})}},Rxa=function(a,b,c){var d=new Image;
d.onload=function(){try{J6(d),c(!0)}catch(e){}};
d.onerror=function(){try{J6(d),c(!1)}catch(e){}};
d.onabort=function(){try{J6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{J6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
exa(d,a)},J6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Txa=function(a){this.o=a;
this.u=new w6},Uxa=function(a){var b=K6(a.o,a.xl,"/mail/images/cleardot.gif");
Y5(b);Sxa(b.toString(),5E3,(0,g.x)(a.xE,a),3,2E3);a.mf(1)},M6=function(a){var b=a.o.J;
if(null!=b)C6(5),b?(C6(11),L6(a.o,a,!1)):(C6(12),L6(a.o,a,!0));else if(a.Xd=new y6(a,void 0,void 0,void 0),a.Xd.Ji=a.As,b=a.o,b=K6(b,b.Vm()?a.Tl:null,a.Bs),C6(5),!g.me||g.Qd(10))Z5(b,"TYPE","xmlhttp"),z6(a.Xd,b,!1,a.Tl,!1);else{Z5(b,"TYPE","html");var c=a.Xd;a=!!a.Tl;c.Yk=3;c.dh=Y5(b.clone());Pxa(c,a)}},N6=function(a){g.lf.call(this);
this.headers=new g.Rm;this.V=a||null;this.A=!1;this.T=this.o=null;this.ga=this.J="";this.D=0;this.B="";this.C=this.aa=this.H=this.W=!1;this.G=0;this.R=null;this.ea="";this.N=this.ba=!1},Vxa=function(a){return g.me&&g.Pd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Wxa=function(a){return"content-type"==a.toLowerCase()},Yxa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.D=5;Xxa(a);O6(a)},Xxa=function(a){a.W||(a.W=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},$xa=function(a){if(a.A&&"undefined"!=typeof g.B1)if(a.T[1]&&4==P6(a)&&2==a.getStatus())Q6(a,"Local request error detected and ignored");
else if(a.H&&4==P6(a))g.Yf(a.fB,0,a);else if(a.dispatchEvent("readystatechange"),4==P6(a)){Q6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.rd(1,String(a.J));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!Zxa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.D=6;try{var l=2<P6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";Xxa(a)}}finally{O6(a)}}},O6=function(a,b){if(a.o){aya(a);
var c=a.o,d=a.T[0]?g.Ia:null;a.o=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},aya=function(a){a.o&&a.N&&(a.o.ontimeout=null);
a.R&&(g.v.clearTimeout(a.R),a.R=null)},P6=function(a){return a.o?a.o.readyState:0},R6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},Q6=function(a,b){return b+" ["+a.ga+" "+a.J+" "+a.getStatus()+"]"},S6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new w6;this.H=a||null;this.J=null!=b?b:null;this.D=c||!1},bya=function(a,b){this.o=a;
this.map=b;this.context=null},cya=function(a){g.Ne.call(this,"statevent",a)},dya=function(a,b){g.Ne.call(this,"timingevent",a);
this.size=b},eya=function(a){g.Ne.call(this,"serverreachability",a)},hya=function(a){fya(a);
if(3==a.o){var b=a.Bm++,c=a.fo.clone();X5(c,"SID",a.A);X5(c,"RID",b);X5(c,"TYPE","terminate");T6(a,c);b=new y6(a,a.A,b,void 0);b.Yk=2;b.dh=Y5(c.clone());exa(new Image,b.dh.toString());b.Sk=(0,g.C)();A6(b)}gya(a)},iya=function(a){a.VE(1,0);
a.fo=K6(a,null,a.zs);U6(a)},fya=function(a){a.gh&&(a.gh.abort(),a.gh=null);
a.oc&&(a.oc.cancel(),a.oc=null);a.kg&&(g.v.clearTimeout(a.kg),a.kg=null);V6(a);a.Rd&&(a.Rd.cancel(),a.Rd=null);a.mh&&(g.v.clearTimeout(a.mh),a.mh=null)},jya=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new bya(a.RJ++,b));2!=a.o&&3!=a.o||U6(a)},U6=function(a){a.Rd||a.mh||(a.mh=H6((0,g.x)(a.qB,a),0),a.Qj=0)},lya=function(a,b){if(1==a.o){if(!b){a.Bm=Math.floor(1E5*Math.random());
var c=a.Bm++,d=new y6(a,"",c,void 0);d.Ji=null;var e=W6(a),f=a.fo.clone();X5(f,"RID",c);X5(f,"CVER","1");T6(a,f);Kxa(d,f,e);a.Rd=d;a.o=2}}else 3==a.o&&(b?kya(a,b):0==a.u.length||a.Rd||kya(a))},kya=function(a,b){if(b)if(6<a.vi){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Bm-1;var d=W6(a)}else c=b.H,d=b.mj;else c=a.Bm++,d=W6(a);var e=a.fo.clone();X5(e,"SID",a.A);X5(e,"RID",c);X5(e,"AID",a.ik);T6(a,e);c=new y6(a,a.A,c,a.Qj+1);c.Ji=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Rd=c;Kxa(c,e,d)},T6=function(a,b){if(a.Bd){var c=a.Bd.Bx();
c&&g.Bb(c,function(d,e){X5(b,e,d)})}},W6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.vi&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.vi?e:f-d;try{g.Bb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},mya=function(a){a.oc||a.kg||(a.G=1,a.kg=H6((0,g.x)(a.pB,a),0),a.Ej=0)},X6=function(a){if(a.oc||a.kg||3<=a.Ej)return!1;
a.G++;a.kg=H6((0,g.x)(a.pB,a),nya(a,a.Ej));a.Ej++;return!0},L6=function(a,b,c){a.Gq=c;
a.Ff=b.Bg;a.D||iya(a)},V6=function(a){null!=a.Ai&&(g.v.clearTimeout(a.Ai),a.Ai=null)},nya=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Y6=function(a,b){if(2==b||9==b){var c=null;
a.Bd&&(c=null);var d=(0,g.x)(a.FO,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),Y5(c));Rxa(c.toString(),1E4,d)}else C6(2);oya(a,b)},oya=function(a,b){a.o=0;
a.Bd&&a.Bd.Ow(b);gya(a);fya(a)},gya=function(a){a.o=0;
a.Ff=-1;if(a.Bd)if(0==a.B.length&&0==a.u.length)a.Bd.wr();else{g.kb(a.B);var b=g.kb(a.u);a.B.length=0;a.u.length=0;a.Bd.wr(b)}},K6=function(a,b,c){var d=g.bn(c);
if(""!=d.o)b&&g.Wm(d,b+"."+d.o),g.Xm(d,d.B);else{var e=window.location;d=ixa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ll&&g.Bb(a.Ll,function(f,h){X5(d,h,f)});
X5(d,"VER",a.vi);T6(a,d);return d},H6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},C6=function(a){Z6.dispatchEvent(new cya(Z6,a))},pya=function(){},qya=function(){this.o=[];
this.u=[]},rya=function(a,b){this.action=a;
this.params=b||{}},$6=function(a,b){g.z.call(this);
this.o=new g.H(this.eN,0,this);g.A(this,this.o);this.Fd=5E3;this.u=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},a7=function(a,b,c){this.R=a;
this.D=b;this.A=new g.Yn;this.u=new $6(this.hO,this);this.o=null;this.Gb=!1;this.C=null;this.J="";this.H=this.B=0;this.G=[];this.N=c||!1},sya=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Gq,sessionId:a.o.A,arrayId:a.o.ik}},tya=function(a,b){a.H=b||0;
a.u.stop();a.o&&(3==a.o.o&&lya(a.o),hya(a.o));a.H=0},b7=function(a){return!!a.o&&3==a.o.o},uya=function(a,b){(a.D.loungeIdToken=b)||a.u.stop()},c7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.rd(4,a))||"";b&&(this.port=":"+b);this.domain=g.sd(a)||"";a=g.Nc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.vc(a,"10.0")&&(this.u=!1))},d7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Cd(c+b,{})},e7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.A,e),qe:g.Qa(a.C,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xq(b,a)},yya=function(){var a=vya;
wya();f7.push(a);xya(f7)},g7=function(a,b){wya();
var c=f7,d=zya(a,String(b));g.db(c)?Aya(d):(xya(c),(0,g.y)(c,function(e){e(d)}))},wya=function(){f7||(f7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",f7,void 0))},Aya=function(a){var b=(h7+1)%50;
h7=b;i7[b]=a;j7||(j7=49==b)},xya=function(a){var b=i7;
if(b[0]){var c=h7,d=j7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
i7=Array(50);h7=-1;j7=!1}},zya=function(a,b){var c=((0,g.C)()-Bya)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},k7=function(a){g.N.call(this);
this.D=a;this.screens=[]},Cya=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},Dya=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.ze)(a.screens,function(f){return!!i6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Cya(a,b[d])||c;return c},Eya=function(a,b){var c=a.screens.length;
a.screens=(0,g.ze)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},l7=function(a,b,c,d){g.N.call(this);
this.D=a;this.B=b;this.C=c;this.A=d;this.u=0;this.o=null;this.Ia=NaN},n7=function(a){k7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;m7(this);this.info("Initializing with "+g6(this.screens))},Fya=function(a){if(a.screens.length){var b=(0,g.Hc)(a.screens,function(d){return d.id}),c=d7(a.u,"/pairing/get_lounge_token_batch");
e7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.JF,a),(0,g.x)(a.IF,a))}},m7=function(a){var b=oxa(uxa());
b=(0,g.ze)(b,function(c){return!c.uuid});
return Dya(a,b)},o7=function(a,b){wxa((0,g.Hc)(a.screens,mxa));
b&&vxa()},q7=function(a,b){g.N.call(this);
this.D=b;var c=g.ws("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.D(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.bb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;p7("Initialized with "+g.Ok(this.o))},Gya=function(a,b,c){var d=d7(a.C,"/pairing/get_screen_availability");
e7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},r7=function(a,b){a:if($5(b)!=$5(a.o))var c=!1;
else{c=g.Ib(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(p7("Updated online screens: "+g.Ok(a.o)),a.o=b,a.S("screenChange"));Hya(a)},s7=function(a){isNaN(a.A)||g.Oo(a.A);
a.A=g.Mo((0,g.x)(a.Hu,a),0<a.B&&a.B<(0,g.C)()?2E4:1E4)},p7=function(a){g7("OnlineScreenService",a)},Iya=function(a){var b={};
(0,g.y)(a.D(),function(c){c.token?b[c.token]=c.id:this.ac("Requesting availability of screen w/o lounge token.")});
return b},Hya=function(a){a=g.Ib(g.Cb(a.o,function(b){return b}));
g.ub(a);a.length?g.vs("yt-remote-online-screen-ids",a.join(","),60):g.xs("yt-remote-online-screen-ids")},t7=function(a){k7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};Jya(this)},Lya=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.ie();if(h=(c?j6(h,c):null)||j6(h,b)){h.uuid=b;var l=u7(a,h);Gya(a.o,l,function(m){e(m?l:null)})}else c?Kya(a,c,(0,g.x)(function(m){var n=u7(this,new d6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Gya(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},Mya=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},Kya=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.xq(d7(a.C,"/pairing/get_lounge_token_batch"),e)},Nya=function(a){a.screens=a.u.ie();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+g6(a.screens))},Jya=function(a){v7(a);
a.u=new n7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.RF,a));Nya(a);a.A=oxa(g.ws("yt-remote-automatic-screen-cache")||[]);v7(a);a.info("Initializing automatic screens: "+g6(a.A));a.o=new q7(a.C,(0,g.x)(a.ie,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},u7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=j6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.vs("yt-remote-automatic-screen-cache",(0,g.Hc)(a.A,mxa)));v7(a);a.B[b.uuid]=b.id;g.vs("yt-remote-device-id-map",a.B,31536E3);return b},v7=function(a){a.B=g.ws("yt-remote-device-id-map")||{}},w7=function(a,b,c){g.N.call(this);
this.T=c;this.J=a;this.u=b;this.H=null},x7=function(a,b){g7(a.T,b)},y7=function(a,b){w7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.lP,this);this.B=(0,g.x)(this.BN,this);this.A=g.Mo((0,g.x)(function(){Oya(this,null)},this),12E4)},Pya=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ok(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){x7(this,"Failed to send message: getMdxSessionStatus.")},a)):x7(a,"Sending yt message without session: "+g.Ok(b))},Oya=function(a,b){g.Oo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.Pp,a),d=(0,g.x)(a.pe,a);a.Vx(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},z7=function(a,b,c){w7.call(this,a,b,"DialSession");
this.A=this.G=null;this.R="";this.V=c;this.B=null;this.D=g.Ia;this.C=NaN;this.N=(0,g.x)(this.oP,this);this.o=g.Ia},Qya=function(a){a.o=a.J.oD(a.R,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ia;
this.Pp(b)},a),(0,g.x)(function(b){this.o=g.Ia;
this.pe(b)},a))},Rya=function(a){var b={};
b.pairingCode=a.R;b.theme=a.V;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}yxa()&&(b.env_useStageMdx=1);return g.Ad(b)},A7=function(a,b){w7.call(this,a,b,"ManualSession");
this.o=g.Mo((0,g.x)(this.jk,this,null),150)},B7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.D=c||"cl";this.H=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.sM,this)},Sya=function(a,b){return b?g.Za(a.A,function(c){return e6(b,c.label)},a):null},C7=function(a){g7("Controller",a)},vya=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},D7=function(a){return a.C||!!a.A.length||!!a.o},E7=function(a,b,c){b!=a.o&&(g.Le(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.oB,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.jk(null)):a.S("yt-remote-cast2-session-change",null))},Tya=function(a){var b=a.u.nD(),c=a.o&&a.o.u;
a=(0,g.Hc)(b,function(d){c&&e6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Sya(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Zya=function(a,b,c,d,e,f,h){Uya()?Vya(b,e,f,h)&&(G7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Wya(a,c):(window.__onGCastApiAvailable=function(l,m){l?Wya(a,c):(H7("Failed to load cast API: "+m),I7(!1),G7(!1),g.xs("yt-remote-cast-available"),g.xs("yt-remote-cast-receiver"),Xya(),c(!1))},d?g.Yo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Fxa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?r6():(Exa(),q6(Yya.map(Cxa))))):F7("Cannot initialize because not running Chrome")},Xya=function(){F7("dispose");
var a=J7();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);$ya(!1);g.Uo(K7);K7.length=0},L7=function(){return!!g.ws("yt-remote-cast-installed")},aza=function(){var a=g.ws("yt-remote-cast-receiver");
return a?a.friendlyName:null},bza=function(){F7("clearCurrentReceiver");
g.xs("yt-remote-cast-receiver")},cza=function(){return L7()?J7()?J7().getCastSession():(H7("getCastSelector: Cast is not initialized."),null):(H7("getCastSelector: Cast API is not installed!"),null)},N7=function(){L7()?J7()?M7()?(F7("Requesting cast selector."),J7().requestSession()):(F7("Wait for cast API to be ready to request the session."),K7.push(g.To("yt-remote-cast2-api-ready",N7))):H7("requestCastSelector: Cast is not initialized."):H7("requestCastSelector: Cast API is not installed!")},O7=
function(a,b){M7()?J7().setConnectedScreenStatus(a,b):H7("setConnectedScreenStatus called before ready.")},Uya=function(){var a=0<=g.Nc.search(/ (CrMo|Chrome|CriOS)\//);
return g.rt||a},dza=function(a,b){J7().init(a,b)},Vya=function(a,b,c,d){var e=!1;
J7()||(a=new B7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.vs("yt-remote-cast-available",f);b6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){F7("onReceiverSelected: "+f.friendlyName);
g.vs("yt-remote-cast-receiver",f);b6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){F7("onReceiverResumed: "+f.friendlyName);
g.vs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){F7("onSessionChange: "+f6(f));
f||g.xs("yt-remote-cast-receiver");b6("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
F7("cloudview.createSingleton_: "+e);return e},J7=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},Wya=function(a,b){I7(!0);
G7(!1);dza(a,function(c){c?($ya(!0),g.Vo("yt-remote-cast2-api-ready")):(H7("Failed to initialize cast API."),I7(!1),g.xs("yt-remote-cast-available"),g.xs("yt-remote-cast-receiver"),Xya());b(c)})},F7=function(a){g7("cloudview",a)},H7=function(a){g7("cloudview",a)},I7=function(a){F7("setCastInstalled_ "+a);
g.vs("yt-remote-cast-installed",a)},M7=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},$ya=function(a){F7("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},G7=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},P7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.D=this.G=0;this.o=null;this.hasNext=this.Gf=!1;this.J=this.H=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},Q7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Gf=!1;a.hasNext=!1;a.G=0;a.D=(0,g.C)();a.C=0;a.u=0;a.H=0;a.J=0;a.B=NaN;a.A=!1},R7=function(a){return a.fb()?((0,g.C)()-a.D)/1E3:0},S7=function(a,b){a.G=b;
a.D=(0,g.C)()},T7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.D)/1E3+a.G;
case -1E3:return 0}return a.G},U7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&Q7(a)},V7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Sb(a.o);b.hasPrevious=a.Gf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.D;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},X7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.D=[];this.C=new qya;this.A=this.u=null;this.J=(0,g.x)(this.yK,this);this.G=(0,g.x)(this.Cm,this);this.H=(0,g.x)(this.xK,this);this.R=(0,g.x)(this.IK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Dv,this),eza(this))):c=3;0!=c&&(b?this.Dv(c):g.Mo((0,g.x)(function(){this.Dv(c)},this),0));
var d=cza();d&&W7(this,d);this.subscribe("yt-remote-cast2-session-change",this.R)},Y7=function(a){return new P7(a.B.getPlayerContextData())},eza=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.D.push(this.B.subscribe(b,g.Qa(this.pM,b),this))},a)},fza=function(a){(0,g.y)(a.D,function(b){this.B.unsubscribeByKey(b)},a);
a.D.length=0},Z7=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},a8=function(a,b,c){var d=Y7(a);
S7(d,c);-1E3!=d.playerState&&(d.playerState=b);$7(a,d)},b8=function(a,b,c){a.B.sendMessage(b,c)},$7=function(a,b){fza(a);
a.B.setPlayerContextData(V7(b));eza(a)},W7=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.G),a.Cm(null));
a.A=b;a.A&&(g7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.G),a.A.media.length&&a.Cm(a.A.media[0]))},gza=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=Y7(a);b.contentId!=d.videoId&&g7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;S7(d,a.u.getEstimatedTime());$7(a,d)}else g7("CP","No cast media video. Ignoring state update.")},c8=function(a,b,c){return(0,g.x)(function(d){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),b8(this,b,c))},a)},d8=function(a,b,c){g.N.call(this);
this.C=NaN;this.N=!1;this.H=this.G=this.J=this.R=NaN;this.T=[];this.B=this.D=this.A=this.Xa=this.o=null;this.W=a;this.T.push(g.ip(window,"beforeunload",(0,g.x)(this.BF,this)));this.u=[];this.Xa=new P7;this.V=b.id;this.o=hza(this,c);this.o.subscribe("handlerOpened",this.CK,this);this.o.subscribe("handlerClosed",this.zK,this);this.o.subscribe("handlerError",this.AK,this);this.o.subscribe("handlerMessage",this.BK,this);uya(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Xa.videoId;
g.ys()&&g.vs("yt-remote-session-video-id",d)},this)},e8=function(a){g7("conn",a)},hza=function(a,b){return new a7(d7(a.W,"/bc"),b)},f8=function(a,b){a.S("proxyStateChange",b)},iza=function(a){a.C=g.Mo((0,g.x)(function(){e8("Connecting timeout");
this.Lj(1)},a),2E4)},g8=function(a){g.Oo(a.C);
a.C=NaN},h8=function(a){g.Oo(a.R);
a.R=NaN},jza=function(a){i8(a);
a.J=g.Mo((0,g.x)(function(){j8(this,"getNowPlaying")},a),2E4)},i8=function(a){g.Oo(a.J);
a.J=NaN},lza=function(a,b){b&&(g8(a),h8(a));
b==(b7(a.o)&&isNaN(a.C))?b&&(f8(a,1),j8(a,"getSubtitlesTrack")):b?(a.Tx()&&a.Xa.reset(),f8(a,1),j8(a,"getNowPlaying"),kza(a)):a.Lj(1)},mza=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Xa.videoId&&(g.Ob(b.params)?a.Xa.o=null:a.Xa.o=b.params,a.S("remotePlayerChange"))},nza=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Xa.listId=b.params.listId||a.Xa.listId;U7(a.Xa,c,d);a.S("remoteQueueChange")},pza=function(a,b){b.params=b.params||{};
nza(a,b);oza(a,b);a.S("autoplayDismissed")},oza=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
S7(a.Xa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Xa.playerState&&(c=-1E3);a.Xa.playerState=c;c=Number(b.params.loadedTime);a.Xa.J=isNaN(c)?0:c;c=Number(b.params.duration);a.Xa.H=isNaN(c)?0:c;c=a.Xa;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.Xa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Xa.playerState?jza(a):i8(a);a.S("remotePlayerChange")},qza=function(a,b){if(-1E3!=
a.Xa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Xa.playerState=c;c=parseInt(b.params.currentTime,10);S7(a.Xa,isNaN(c)?0:c);a.S("remotePlayerChange")}},rza=function(a,b){var c="true"==b.params.muted;
a.Xa.volume=parseInt(b.params.volume,10);a.Xa.muted=c;a.S("remotePlayerChange")},sza=function(a,b){a.D=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},tza=function(a,b){var c="true"==b.params.hasNext;
a.Xa.Gf="true"==b.params.hasPrevious;a.Xa.hasNext=c;a.S("previousNextChange")},kza=function(a){g.Oo(a.H);
a.H=g.Mo((0,g.x)(a.Lj,a,1),864E5)},j8=function(a,b,c){c?e8("Sending: action="+b+", params="+g.Ok(c)):e8("Sending: action="+b);
a.o.sendMessage(b,c)},k8=function(a){k7.call(this,"ScreenServiceProxy");
this.Ed=a;this.o=[];this.o.push(this.Ed.$_s("screenChange",(0,g.x)(this.jP,this)));this.o.push(this.Ed.$_s("onlineScreenChange",(0,g.x)(this.TL,this)))},yza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;qxa();n6();l8||(l8=new c7(b?b.loungeApiHost:void 0),yxa()&&(l8.o="/api/loungedev"));m8||(m8=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",m8,void 0));uza();var c=n8();if(!c){var d=new t7(l8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=n8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);Zya(a,d,function(m){m?o8()&&O7(o8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){b6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),p8("Initializing: "+g.Ok(b)),q8.push(g.To("yt-remote-cast2-availability-change",function(){b6("yt-remote-receiver-availability-change")})),q8.push(g.To("yt-remote-cast2-receiver-selected",function(){r8(null);
b6("yt-remote-auto-connect","cast-selector-receiver")})),q8.push(g.To("yt-remote-cast2-receiver-resumed",function(){b6("yt-remote-receiver-resumed","cast-selector-receiver")})),q8.push(g.To("yt-remote-cast2-session-change",vza)),q8.push(g.To("yt-remote-connection-change",function(m){m?O7(o8(),"YouTube TV"):s8()||(O7(null,null),bza())})),a=t8(),b.isAuto&&(a.id+="#dial"),g.Co("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),p8(" -- with channel params: "+
g.Ok(a)),wza(a),c.start(),o8()||xza())},Aza=function(){var a=zza();
L7()&&g.ws("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},zza=function(){var a=n8().Ed.$_gos();
var b=u8();b&&v8()&&(i6(a,b)||a.push(b));return pxa(a)},w8=function(){var a=Bza();
!a&&L7()&&aza()&&(a={key:"cast-selector-receiver",name:aza()});return a},Bza=function(){var a=zza(),b=u8();
b||(b=s8());return g.Za(a,function(c){return b&&e6(b,c.key)?!0:!1})},u8=function(){var a=o8();
if(!a)return null;var b=n8().ie();return j6(b,a)},vza=function(a){p8("remote.onCastSessionChange_: "+f6(a));
if(a){var b=u8();b&&b.id==a.id?O7(b.id,"YouTube TV"):(b&&x8(),y8(a,1))}else v8()&&x8()},x8=function(){M7()?J7().stopSession():H7("stopSession called before API ready.");
var a=v8();a&&(a.disconnect(1),z8(null))},A8=function(){var a=v8();
return!!a&&3!=a.getProxyState()},p8=function(a){g7("remote",a)},n8=function(){if(!B8){var a=g.Ha("yt.mdx.remote.screenService_");
B8=a?new k8(a):null}return B8},o8=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},Cza=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},Dza=function(){return g.Ha("yt.mdx.remote.connectData_")},r8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},v8=function(){return g.Ha("yt.mdx.remote.connection_")},z8=function(a){var b=v8();
r8(null);a||Cza("");g.Fa("yt.mdx.remote.connection_",a,void 0);m8&&((0,g.y)(m8,function(c){c(a)}),m8.length=0);
b&&!a?b6("yt-remote-connection-change",!1):!b&&a&&b6("yt-remote-connection-change",!0)},s8=function(){var a=g.ys();
if(!a)return null;var b=n8();if(!b)return null;b=b.ie();return j6(b,a)},y8=function(a,b){o8();
u8()&&u8();if(C8)D8=a;else{Cza(a.id);var c=new d8(l8,a,t8());c.connect(b,Dza());c.subscribe("beforeDisconnect",function(d){b6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){v8()&&(v8(),z8(null))});
z8(c)}},xza=function(){var a=s8();
a?(p8("Resume connection to: "+f6(a)),y8(a,0)):(o6(),bza(),p8("Skipping connecting because no session screen found."))},uza=function(){var a=t8();
if(g.Ob(a)){a=m6();var b=g.ws("yt-remote-session-name")||"",c=g.ws("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},t8=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},wza=function(a){a?(g.vs("yt-remote-session-app",a.app),g.vs("yt-remote-session-name",a.name)):(g.xs("yt-remote-session-app"),g.xs("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},E8=function(a,b,c){g.z.call(this);
var d=this;this.module=a;this.K=b;this.Ra=c;this.events=new g.zr(this);this.J=this.events.M(this.K,"onVolumeChange",this.OA);this.B=!1;this.suggestion=null;this.C=new g.FC(64);this.o=new g.H(this.uC,500,this);this.u=new g.H(this.vC,1E3,this);this.G=new s6(this.MO,0,this);this.A={};this.H=new g.H(this.ZC,1E3,this);this.D=new t6(this.seekTo,1E3,this);this.R=g.Ia;g.A(this,this.events);this.events.M(b,"onCaptionsTrackListChanged",this.tL);this.events.M(b,"captionschanged",this.wK);this.events.M(b,"captionssettingschanged",
this.wC);this.events.M(b,"videoplayerreset",this.Qp);this.events.M(b,"mdxautoplaycancel",function(){d.Ra.hx()});
a=this.Ra;a.ha();a.subscribe("proxyStateChange",this.iB,this);a.subscribe("remotePlayerChange",this.Gm,this);a.subscribe("remoteQueueChange",this.Qp,this);a.subscribe("previousNextChange",this.eB,this);a.subscribe("nowAutoplaying",this.aB,this);a.subscribe("autoplayDismissed",this.yA,this);g.A(this,this.o);g.A(this,this.u);g.A(this,this.G);g.A(this,this.H);g.A(this,this.D);this.wC();this.Qp();this.Gm()},Eza=function(a){a.Ub(0);
a.o.stop();F8(a,new g.FC(64))},H8=function(a,b){if(G8(a)&&!a.B){var c=null;
b&&(c={style:a.K.getSubtitlesUserSettings()},g.Ub(c,b));a.Ra.lD(a.K.getVideoData(1).videoId,c);a.A=Y7(a.Ra).o}},I8=function(a,b){var c=a.K.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.K.getVideoData(1);a.Ra.playVideo(c.videoId,b,d,e,c.playerParams,c.Hf,cxa(c));F8(a,new g.FC(1))},Fza=function(a,b){if(b){var c=a.K.getOption("captions","tracklist",{ty:1});
c&&c.length?(a.K.setOption("captions","track",b),a.B=!1):(a.K.loadModule("captions"),a.B=!0)}else a.K.setOption("captions","track",{})},G8=function(a){return Y7(a.Ra).videoId===a.K.getVideoData(1).videoId},F8=function(a,b){a.u.stop();
var c=a.C;if(!g.LC(c,b)){var d=g.U(b,2);d!==g.U(a.C,2)&&g.fT(a.K.app,d);a.C=b;Gza(a.module,c,b)}},J8=function(){g.Q.call(this,{F:"div",
I:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},L:[{F:"div",I:"ytp-mdx-manual-pairing-popup-dialog-inner-content",L:[{F:"div",I:"ytp-mdx-manual-pairing-popup-title",X:"Connecting to your TV on web using a code will be going away soon"},{F:"div",I:"ytp-mdx-manual-pairing-popup-buttons",L:[{F:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],X:"Learn more"},{F:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],X:"OK"}]}]}]});this.u=new g.yN(this,250);this.learnMoreButton=
this.o["ytp-mdx-manual-pairing-popup-learn-more"];this.okButton=this.o["ytp-mdx-manual-pairing-popup-ok"];g.A(this,this.u);this.M(this.learnMoreButton,"click",this.A);this.M(this.okButton,"click",this.B)},K8=function(){g.Q.call(this,{F:"div",
I:"ytp-mdx-popup-dialog",P:{role:"dialog"},L:[{F:"div",I:"ytp-mdx-popup-dialog-inner-content",L:[{F:"div",I:"ytp-mdx-popup-title",X:"You're signed out"},{F:"div",I:"ytp-mdx-popup-description",X:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{F:"div",I:"ytp-mdx-privacy-popup-buttons",L:[{F:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],X:"Cancel"},{F:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
X:"Confirm"}]}]}]});this.u=new g.yN(this,250);this.cancelButton=this.o["ytp-mdx-privacy-popup-cancel"];this.confirmButton=this.o["ytp-mdx-privacy-popup-confirm"];g.A(this,this.u);this.M(this.cancelButton,"click",this.A);this.M(this.confirmButton,"click",this.B)},L8=function(a){g.Q.call(this,{F:"div",
I:"ytp-remote",L:[{F:"div",I:"ytp-remote-display-status",L:[{F:"div",I:"ytp-remote-display-status-icon",L:[g.SM()]},{F:"div",I:"ytp-remote-display-status-text",X:"{{statustext}}"}]}]});this.api=a;this.u=new g.yN(this,250);g.A(this,this.u);this.M(a,"presentingplayerstatechange",this.A);Hza(this,g.iL(a))},Hza=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.zM("Error on $RECEIVER_NAME",c):b.fb()||g.U(b,4)?g.zM("Playing on $RECEIVER_NAME",c):g.zM("Connected to $RECEIVER_NAME",c);a.oa("statustext",c);a.u.show()}else a.u.hide()},M8=function(a,b){g.rP.call(this,"Play on",0,a,b);
this.K=a;this.Yh={};this.M(a,"onMdxReceiversChange",this.D);this.M(a,"presentingplayerstatechange",this.D);this.D()},N8=function(a){g.OL.call(this,a);
this.hf={key:h6(),name:"This computer"};this.ce=null;this.subscriptions=[];this.tu=this.Ra=null;this.Yh=[this.hf];this.jh=this.hf;this.Kb=new g.FC(64);this.Ky=0;this.Vc=-1;this.lk=null;this.Hm=this.Wo=!1;this.lj=this.Nk=null;if(!g.Xy(this.player.O())){a=this.player;var b=g.cC(a);b&&(b=b.sm())&&(b=new M8(a,b),g.A(this,b));b=new L8(a);g.A(this,b);g.CL(a,b.element,4);this.Nk=new K8;g.A(this,this.Nk);g.CL(a,this.Nk.element,4);g.O(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.lk=new J8,g.A(this,this.lk),g.CL(a,this.lk.element,4));this.Hm=!!s8();this.Wo=!!g.ws("yt-remote-manual-pairing-warning-shown")}},O8=function(a){a.lj&&(a.player.removeEventListener("presentingplayerstatechange",a.lj),a.lj=null)},Gza=function(a,b,c){a.Kb=c;
a.player.S("presentingplayerstatechange",new g.hH(c,b))},Iza=function(a,b,c){var d=!1;
1===b?d=!a.Hm:2===b&&(d=!a.Wo);d&&g.jH(c,8)&&(a.player.pauseVideo(),O8(a))},P8=function(a,b){if(b.key!==a.jh.key)if(b.key===a.hf.key)x8();
else{if(a.lk&&!a.Wo&&b!==a.hf&&"cast-selector-receiver"!==b.key&&g.fz(a.player.O()))Jza(a);else{var c;(c=!g.O(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Hm||!a.Nk);(c?0:g.fz(a.player.O())||g.jz(a.player.O()))&&Kza(a)}a.jh=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.O(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ca(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Hf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=cxa(c))&&(d.locationInfo=c);c=d}p8("Connecting to: "+g.Ok(b));"cast-selector-receiver"==b.key?(r8(c||null),c=
c||null,M7()?J7().setLaunchParams(c):H7("setLaunchParams called before ready.")):!c&&A8()&&o8()==b.key?b6("yt-remote-connection-change",!0):(x8(),r8(c||null),c=n8().ie(),(c=j6(c,b.key))&&y8(c,1))}},Kza=function(a){g.iL(a.player).fb()?a.player.pauseVideo():(a.lj=function(b){Iza(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.lj));
a.Nk&&a.Nk.Wb();v8()||(C8=!0)},Jza=function(a){g.iL(a.player).fb()?a.player.pauseVideo():(a.lj=function(b){Iza(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.lj));
a.lk&&a.lk.Wb();v8()||(C8=!0)},Oxa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},G6={"'":"\\'"},Lza={},lxa={TP:"atp",hT:"ska",QS:"que",eS:"mus",gT:"sus",fR:"dsp",ZS:"seq"},p6,l6="",Dxa=zxa("loadCastFramework")||zxa("loadCastApplicationFramework"),Yya=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(s6,g.z);g.k=s6.prototype;g.k.yF=function(a){this.B=arguments;this.o=!1;this.Ia?this.A=(0,g.C)()+this.Fd:this.Ia=g.Yf(this.C,this.Fd)};
g.k.stop=function(){this.Ia&&(g.v.clearTimeout(this.Ia),this.Ia=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.D.apply(null,this.B)))};
g.k.Z=function(){this.stop();s6.Nb.Z.call(this)};
g.k.zF=function(){this.A?(this.Ia=g.Yf(this.C,this.A-(0,g.C)()),this.A=null):(this.Ia=null,this.u?this.o=!0:(this.o=!1,this.D.apply(null,this.B)))};g.r(t6,g.z);g.k=t6.prototype;g.k.Zy=function(a){this.A=arguments;this.Ia||this.u?this.o=!0:u6(this)};
g.k.stop=function(){this.Ia&&(g.v.clearTimeout(this.Ia),this.Ia=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ia||(this.o=!1,u6(this))};
g.k.Z=function(){g.z.prototype.Z.call(this);this.stop()};w6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
w6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};x6.prototype.o=null;x6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Hxa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var Q8;g.Sa(Gxa,x6);Q8=new Gxa;g.k=y6.prototype;g.k.Ji=null;g.k.sf=!1;g.k.kl=null;g.k.Av=null;g.k.Sk=null;g.k.Yk=null;g.k.dh=null;g.k.Zh=null;g.k.mj=null;g.k.Pc=null;g.k.fn=0;g.k.wf=null;g.k.Iq=null;g.k.wh=null;g.k.Ul=-1;g.k.jC=!0;g.k.ti=!1;g.k.Cs=0;g.k.Yp=null;var Mxa={},B6={};g.k=y6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.UN=function(a){a=a.target;var b=this.Yp;b&&3==P6(a)?b.Zy():this.iD(a)};
g.k.iD=function(a){try{if(a==this.Pc)a:{var b=P6(this.Pc),c=this.Pc.D,d=this.Pc.getStatus();if(g.me&&!g.Qd(10)||g.oe&&!g.Pd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ah&&!R6(this.Pc))break a;this.ti||4!=b||7==c||(8==c||0>=d?this.o.mf(3):this.o.mf(2));I6(this);var e=this.Pc.getStatus();this.Ul=e;var f=R6(this.Pc);(this.sf=200==e)?(4==b&&E6(this),this.D?(Nxa(this,b,f),g.Ah&&this.sf&&3==b&&(this.B.na(this.u,"tick",this.NN),this.u.start())):D6(this,f),this.sf&&!this.ti&&(4==b?this.o.wo(this):(this.sf=
!1,A6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.wh=3,C6(13)):(this.wh=0,C6(14)),E6(this),F6(this))}}catch(h){this.Pc&&R6(this.Pc)}finally{}};
g.k.NN=function(){var a=P6(this.Pc),b=R6(this.Pc);this.fn<b.length&&(I6(this),Nxa(this,a,b),this.sf&&4!=a&&A6(this))};
g.k.lN=function(a){H6((0,g.x)(this.kN,this,a),0)};
g.k.kN=function(a){this.ti||(I6(this),D6(this,a),A6(this))};
g.k.rB=function(a){H6((0,g.x)(this.jN,this,a),0)};
g.k.jN=function(a){this.ti||(E6(this),this.sf=a,this.o.wo(this),this.o.mf(4))};
g.k.cancel=function(){this.ti=!0;E6(this)};
g.k.tN=function(){this.kl=null;var a=(0,g.C)();0<=a-this.Av?(2!=this.Yk&&this.o.mf(3),E6(this),this.wh=2,C6(18),F6(this)):Qxa(this,this.Av-a)};
g.k.getLastError=function(){return this.wh};g.k=Txa.prototype;g.k.As=null;g.k.Xd=null;g.k.Zp=!1;g.k.ey=null;g.k.bo=null;g.k.gt=null;g.k.Bs=null;g.k.Be=null;g.k.Bg=-1;g.k.Tl=null;g.k.xl=null;g.k.connect=function(a){this.Bs=a;a=K6(this.o,null,this.Bs);C6(3);this.ey=(0,g.C)();var b=this.o.H;null!=b?(this.Tl=b[0],(this.xl=b[1])?(this.Be=1,Uxa(this)):(this.Be=2,M6(this))):(Z5(a,"MODE","init"),this.Xd=new y6(this,void 0,void 0,void 0),this.Xd.Ji=this.As,z6(this.Xd,a,!1,null,!0),this.Be=0)};
g.k.xE=function(a){if(a)this.Be=2,M6(this);else{C6(4);var b=this.o;b.Ff=b.gh.Bg;Y6(b,9)}a&&this.mf(2)};
g.k.Fr=function(a){return this.o.Fr(a)};
g.k.abort=function(){this.Xd&&(this.Xd.cancel(),this.Xd=null);this.Bg=-1};
g.k.dy=function(){return!1};
g.k.jB=function(a,b){this.Bg=a.Ul;if(0==this.Be)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.Ff=this.Bg;Y6(c,2);return}this.Tl=c[0];this.xl=c[1]}else c=this.o,c.Ff=this.Bg,Y6(c,2);else if(2==this.Be)if(this.Zp)C6(7),this.gt=(0,g.C)();else if("11111"==b){if(C6(6),this.Zp=!0,this.bo=(0,g.C)(),c=this.bo-this.ey,!g.me||g.Qd(10)||500>c)this.Bg=200,this.Xd.cancel(),C6(12),L6(this.o,this,!0)}else C6(8),this.bo=this.gt=(0,g.C)(),this.Zp=!1};
g.k.wo=function(){this.Bg=this.Xd.Ul;if(this.Xd.sf)0==this.Be?this.xl?(this.Be=1,Uxa(this)):(this.Be=2,M6(this)):2==this.Be&&((!g.me||g.Qd(10)?!this.Zp:200>this.gt-this.bo)?(C6(11),L6(this.o,this,!1)):(C6(12),L6(this.o,this,!0)));else{0==this.Be?C6(9):2==this.Be&&C6(10);var a=this.o;this.Xd.getLastError();a.Ff=this.Bg;Y6(a,2)}};
g.k.Vm=function(){return this.o.Vm()};
g.k.isActive=function(){return this.o.isActive()};
g.k.mf=function(a){this.o.mf(a)};g.Sa(N6,g.lf);var Zxa=/^https?$/i,Mza=["POST","PUT"];g.k=N6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.J+"; newUri="+a);b=b?b.toUpperCase():"GET";this.J=a;this.B="";this.D=0;this.ga=b;this.W=!1;this.A=!0;this.o=this.V?Ixa(this.V):Ixa(Q8);this.T=this.V?this.V.getOptions():Q8.getOptions();this.o.onreadystatechange=(0,g.x)(this.fB,this);try{a6(Q6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){a6(Q6(this,"Error opening Xhr: "+f.message));Yxa(this,f);return}a=
c||"";var e=this.headers.clone();d&&hxa(d,function(f,h){e.set(h,f)});
d=g.Za(e.ze(),Wxa);c=g.v.FormData&&a instanceof g.v.FormData;!g.bb(Mza,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.ba&&(this.o.withCredentials=this.ba);try{aya(this),0<this.G&&(this.N=Vxa(this.o),a6(Q6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.N)),this.N?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.fy,this)):this.R=g.Yf(this.fy,this.G,this)),a6(Q6(this,"Sending request")),this.H=!0,this.o.send(a),this.H=!1}catch(f){a6(Q6(this,"Send error: "+f.message)),Yxa(this,f)}};
g.k.fy=function(){"undefined"!=typeof g.B1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.D=8,Q6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(Q6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.D=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),O6(this))};
g.k.Z=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),O6(this,!0));N6.Nb.Z.call(this)};
g.k.fB=function(){this.ha()||(this.aa||this.H||this.C?$xa(this):this.rM())};
g.k.rM=function(){$xa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<P6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=S6.prototype;g.k.Ll=null;g.k.Rd=null;g.k.oc=null;g.k.zs=null;g.k.fo=null;g.k.Cw=null;g.k.vo=null;g.k.Bm=0;g.k.RJ=0;g.k.Bd=null;g.k.mh=null;g.k.kg=null;g.k.Ai=null;g.k.gh=null;g.k.Gq=null;g.k.ik=-1;g.k.Jy=-1;g.k.Ff=-1;g.k.Qj=0;g.k.Ej=0;g.k.vi=8;var Z6=new g.lf;g.Sa(cya,g.Ne);g.Sa(dya,g.Ne);g.Sa(eya,g.Ne);g.k=S6.prototype;g.k.connect=function(a,b,c,d,e){C6(0);this.zs=b;this.Ll=c||{};d&&void 0!==e&&(this.Ll.OSID=d,this.Ll.OAID=e);this.D?(H6((0,g.x)(this.Uw,this,a),100),iya(this)):this.Uw(a)};
g.k.Uw=function(a){this.gh=new Txa(this);this.gh.As=null;this.gh.u=this.C;this.gh.connect(a)};
g.k.dy=function(){return 0==this.o};
g.k.qB=function(a){this.mh=null;lya(this,a)};
g.k.pB=function(){this.kg=null;this.oc=new y6(this,this.A,"rpc",this.G);this.oc.Ji=null;this.oc.Cs=0;var a=this.Cw.clone();X5(a,"RID","rpc");X5(a,"SID",this.A);X5(a,"CI",this.Gq?"0":"1");X5(a,"AID",this.ik);T6(this,a);if(!g.me||g.Qd(10))X5(a,"TYPE","xmlhttp"),z6(this.oc,a,!0,this.vo,!1);else{X5(a,"TYPE","html");var b=this.oc,c=!!this.vo;b.Yk=3;b.dh=Y5(a.clone());Pxa(b,c)}};
g.k.jB=function(a,b){if(0!=this.o&&(this.oc==a||this.Rd==a))if(this.Ff=a.Ul,this.Rd==a&&3==this.o)if(7<this.vi){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.kg){if(this.oc)if(this.oc.Sk+3E3<this.Rd.Sk)V6(this),this.oc.cancel(),this.oc=null;else break a;X6(this);C6(19)}}else this.Jy=c[1],0<this.Jy-this.ik&&37500>c[2]&&this.Gq&&0==this.Ej&&!this.Ai&&(this.Ai=H6((0,g.x)(this.tK,this),6E3));else Y6(this,11)}else b!=Lza.vQ.o&&Y6(this,11);else if(this.oc==
a&&V6(this),!g.kc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ik=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.vo=e[2],e=e[3],null!=e?this.vi=e:this.vi=6,this.o=3,this.Bd&&this.Bd.Qw(),this.Cw=K6(this,this.Vm()?this.vo:null,this.zs),mya(this)):"stop"==e[0]&&Y6(this,7):3==this.o&&("stop"==e[0]?Y6(this,7):"noop"!=e[0]&&this.Bd&&this.Bd.Pw(e),this.Ej=0)}}};
g.k.tK=function(){null!=this.Ai&&(this.Ai=null,this.oc.cancel(),this.oc=null,X6(this),C6(20))};
g.k.wo=function(a){if(this.oc==a){V6(this);this.oc=null;var b=2}else if(this.Rd==a)this.Rd=null,b=1;else return;this.Ff=a.Ul;if(0!=this.o)if(a.sf)1==b?(b=(0,g.C)()-a.Sk,Z6.dispatchEvent(new dya(Z6,a.mj?a.mj.length:0,b,this.Qj)),U6(this),this.B.length=0):mya(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ff)){if(d=1==b)this.Rd||this.mh||1==this.o||2<=this.Qj?d=!1:(this.mh=H6((0,g.x)(this.qB,this,a),nya(this,this.Qj)),this.Qj++,d=!0);d=!(d||2==b&&X6(this))}if(d)switch(c){case 1:Y6(this,
5);break;case 4:Y6(this,10);break;case 3:Y6(this,6);break;case 7:Y6(this,12);break;default:Y6(this,2)}}};
g.k.VE=function(a){if(!g.bb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.FO=function(a){a?C6(2):(C6(1),oya(this,8))};
g.k.Fr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N6;a.ba=!1;return a};
g.k.isActive=function(){return!!this.Bd&&this.Bd.isActive(this)};
g.k.mf=function(a){Z6.dispatchEvent(new eya(Z6,a))};
g.k.Vm=function(){return!(!g.me||g.Qd(10))};
g.k=pya.prototype;g.k.Qw=function(){};
g.k.Pw=function(){};
g.k.Ow=function(){};
g.k.wr=function(){};
g.k.Bx=function(){return{}};
g.k.isActive=function(){return!0};g.k=qya.prototype;g.k.isEmpty=function(){return g.db(this.o)&&g.db(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.bb(this.o,a)||g.bb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Qra)(b,a);0<=c?(g.fb(b,c),b=!0):b=!1;return b||g.gb(this.u,a)};
g.k.Ld=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Sa($6,g.z);g.k=$6.prototype;g.k.eN=function(){this.Fd=Math.min(3E5,2*this.Fd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Fd+15E3*Math.random();this.o.Wa(a);this.u=(0,g.C)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Fd=5E3};g.Sa(a7,pya);g.k=a7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Qh=function(a){return this.A.Ki(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Gb||(this.Gb=!0,g.Le(this.A),tya(this),g.Le(this.u),this.u=null)};
g.k.ha=function(){return this.Gb};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.u.stop();this.C=a||null;this.B=b||0;a=this.R+"/test";b=this.R+"/bind";var d=new S6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Bd=null);d.Bd=this;this.o=d;e?this.o.connect(a,b,this.D,e.A,e.ik):c?this.o.connect(a,b,this.D,c.sessionId,c.arrayId):this.o.connect(a,b,this.D)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Ub(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):b7(this)&&jya(this.o,c)};
g.k.Qw=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)jya(this.o,a[b])}this.S("handlerOpened")};
g.k.Ow=function(a){var b=2==a&&401==this.o.Ff;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.wr=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.Bx=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.C&&g.Ub(a,this.C);return a};
g.k.Pw=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),hya(this.o)):this.S("handlerMessage",new rya(a[0],a[1]))};
g.k.hO=function(){this.u.isActive();var a=this.o,b=0;a.oc&&b++;a.Rd&&b++;0==b&&this.connect(this.C,this.B)};c7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
c7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
c7.prototype.C=function(a){a(Error("request timed out"))};var Bya=(0,g.C)(),f7=null,i7=Array(50),h7=-1,j7=!1;g.Sa(k7,g.N);k7.prototype.ie=function(){return this.screens};
k7.prototype.contains=function(a){return!!i6(this.screens,a)};
k7.prototype.get=function(a){return a?j6(this.screens,a):null};
k7.prototype.info=function(a){g7(this.D,a)};g.r(l7,g.N);g.k=l7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ia)&&this.mD()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.Oo(this.Ia),this.Ia=NaN)};
g.k.Z=function(){this.stop();g.N.prototype.Z.call(this)};
g.k.mD=function(){this.Ia=NaN;this.o=g.xq(d7(this.D,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.hP,this),onError:(0,g.x)(this.gP,this),qe:(0,g.x)(this.iP,this)})};
g.k.hP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.A;this.S("pairingComplete",new d6(c))};
g.k.gP=function(a){this.o=null;a.status&&404==a.status?this.u>=Nza.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=Nza[this.u],this.Ia=g.Mo((0,g.x)(this.mD,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.iP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var Nza=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(n7,k7);g.k=n7.prototype;g.k.start=function(){m7(this)&&this.S("screenChange");!g.ws("yt-remote-lounge-token-expiration")&&Fya(this);g.Oo(this.o);this.o=g.Mo((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){m7(this);Cya(this,a);o7(this,!1);this.S("screenChange");b(a);a.token||Fya(this)};
g.k.remove=function(a,b){var c=m7(this);Eya(this,a)&&(o7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.Eq=function(a,b,c,d){var e=m7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,o7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.Z=function(){g.Oo(this.o);n7.Nb.Z.call(this)};
g.k.JF=function(a){m7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}o7(this,!b);b&&g7(this.D,"Missed "+b+" lounge tokens.")};
g.k.IF=function(a){g7(this.D,"Requesting lounge tokens failed: "+a)};g.r(q7,g.N);g.k=q7.prototype;g.k.start=function(){var a=parseInt(g.ws("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.C)()-144E5<a?0:a)?s7(this):(this.B=(0,g.C)()+3E5,g.vs("yt-remote-fast-check-period",this.B),this.Hu())};
g.k.isEmpty=function(){return g.Ob(this.o)};
g.k.update=function(){p7("Updating availability on schedule.");var a=this.D(),b=g.Cb(this.o,function(c,d){return c&&!!j6(a,d)},this);
r7(this,b)};
g.k.Z=function(){g.Oo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.Z.call(this)};
g.k.Hu=function(){g.Oo(this.A);this.A=NaN;this.u&&this.u.abort();var a=Iya(this);if($5(a)){var b=d7(this.C,"/pairing/get_screen_availability");this.u=e7(this.C,b,{lounge_token:g.Ib(a).join(",")},(0,g.x)(this.OM,this,a),(0,g.x)(this.MM,this))}else r7(this,{}),s7(this)};
g.k.OM=function(a,b){this.u=null;var c=g.Ib(Iya(this));if(g.vb(c,g.Ib(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;r7(this,d);s7(this)}else this.ac("Changing Screen set during request."),this.Hu()};
g.k.MM=function(a){this.ac("Screen availability failed: "+a);this.u=null;s7(this)};
g.k.ac=function(a){g7("OnlineScreenService",a)};g.Sa(t7,k7);g.k=t7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.Eq=function(a,b,c,d){this.u.contains(a)?this.u.Eq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,g7(this.D,a),d(Error(a)))};
g.k.ie=function(a){return a?this.screens:g.jb(this.screens,(0,g.ze)(this.A,function(b){return!this.contains(b)},this))};
g.k.nD=function(){return(0,g.ze)(this.ie(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.oD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new l7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Le(f);d(u7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Le(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.kP=function(a,b,c,d){g.xq(d7(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new d6(f.screen||{});if(!h.name||Mya(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);Mya(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(u7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
qe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.Z=function(){g.Le(this.u);g.Le(this.o);t7.Nb.Z.call(this)};
g.k.RF=function(){Nya(this);this.S("screenChange");this.o.update()};
t7.prototype.dispose=t7.prototype.dispose;g.Sa(w7,g.N);g.k=w7.prototype;g.k.getScreen=function(){return this.H};
g.k.Pp=function(a){this.H=a;this.S("sessionScreen",this.H)};
g.k.pe=function(a){this.ha()||(a&&x7(this,""+a),this.H=null,this.S("sessionScreen",null))};
g.k.info=function(a){g7(this.T,a)};
g.k.qD=function(){return null};
g.k.Ru=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){x7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.Z=function(){this.Ru("");w7.Nb.Z.call(this)};g.Sa(y7,w7);g.k=y7.prototype;g.k.Qu=function(a){if(this.o){if(this.o==a)return;x7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Pya(this)};
g.k.jk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ok(a))};
g.k.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.pe()},this),(0,g.x)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.k.Ru=g.Ia;g.k.Z=function(){this.info("disposeInternal");g.Oo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;y7.Nb.Z.call(this)};
g.k.BN=function(a,b){if(!this.ha())if(b){var c=v6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ok(c));switch(d){case "mdxSessionStatus":Oya(this,c.screenId);break;default:x7(this,"Unknown youtube message: "+d)}}else x7(this,"Unable to parse message.")}else x7(this,"No data in message.")};
g.k.Vx=function(a,b,c,d){Lya(this.J,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(x7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Mo((0,g.x)(this.Vx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.qD=function(){return this.o};
g.k.lP=function(a){this.ha()||a||(x7(this,"Cast session died."),this.pe())};g.Sa(z7,w7);g.k=z7.prototype;g.k.Qu=function(a){this.A=a;this.A.addUpdateListener(this.N)};
g.k.jk=function(a){this.B=a;this.D()};
g.k.stop=function(){this.o();this.o=g.Ia;g.Oo(this.C);this.A?this.A.stop((0,g.x)(this.pe,this,null),(0,g.x)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.k.Z=function(){this.o();this.o=g.Ia;g.Oo(this.C);this.A&&this.A.removeUpdateListener(this.N);this.A=null;z7.Nb.Z.call(this)};
g.k.oP=function(a){this.ha()||a||(x7(this,"DIAL session died."),this.o(),this.o=g.Ia,this.pe())};
g.k.Ms=function(a){this.R=h6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Rya(this));a(b);Qya(this)}else this.D=(0,g.x)(function(){g.Oo(this.C);this.D=g.Ia;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Rya(this));a(c);Qya(this)},this),this.C=g.Mo((0,g.x)(function(){this.D()},this),100)};
g.k.lG=function(a,b,c){Lya(this.J,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Pp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Ms(b,c)},this),(0,g.x)(function(d){x7(this,"Failed to get DIAL screen: "+d);
this.Ms(b,c)},this))};g.Sa(A7,w7);A7.prototype.stop=function(){this.pe()};
A7.prototype.Qu=g.Ia;A7.prototype.jk=function(){g.Oo(this.o);this.o=NaN;var a=j6(this.J.ie(),this.u.label);a?this.Pp(a):this.pe(Error("No such screen"))};
A7.prototype.Z=function(){g.Oo(this.o);this.o=NaN;A7.Nb.Z.call(this)};g.Sa(B7,g.N);g.k=B7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.wM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.mB,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.PK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),yya(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.pD,this)),this.A=Tya(this),chrome.cast.setCustomReceivers(this.A,g.Ia,(0,g.x)(function(h){this.ac("Failed to set initial custom receivers: "+g.Ok(h))},this)),this.S("yt-remote-cast2-availability-change",D7(this)),b(!0))},this),(0,g.x)(function(h){this.ac("Failed to initialize API: "+g.Ok(h));
b(!1)},this))};
g.k.pO=function(a,b){C7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)C7("Unsetting old screen status: "+this.o.u.friendlyName),E7(this,null)}if(a&&b){if(!this.o){c=j6(this.u.ie(),a);if(!c){C7("setConnectedScreenStatus: Unknown screen.");return}var d=Sya(this,c);d||(C7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ia,(0,g.x)(function(e){this.ac("Failed to set initial custom receivers: "+g.Ok(e))},this)));
C7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);E7(this,new A7(this.u,d),!0)}this.o.Ru(b)}else C7("setConnectedScreenStatus: no screen.")};
g.k.qO=function(a){this.ha()?this.ac("Setting connection data on disposed cast v2"):this.o?this.o.jk(a):this.ac("Setting connection data without a session")};
g.k.nP=function(){this.ha()?this.ac("Stopping session on disposed cast v2"):this.o?(this.o.stop(),E7(this,null)):C7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.mB,this),(0,g.x)(this.RM,this))};
g.k.Z=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.pD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=vya,b=g.Ha("yt.mdx.remote.debug.handlers_");g.gb(b||[],a);g.Le(this.o);B7.Nb.Z.call(this)};
g.k.ac=function(a){g7("Controller",a)};
g.k.oB=function(a,b){this.o==a&&(b||E7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.sM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),C7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)C7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{C7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:E7(this,
new A7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:E7(this,new z7(this.u,a,this.D));break;case chrome.cast.ReceiverType.CAST:E7(this,new y7(this.u,a));break;default:this.ac("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.ac("Stopping receiver w/o session: "+a.friendlyName)}else this.ac("onReceiverAction_ called without receiver.")};
g.k.PK=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.ac("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.ac("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return C7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.ac('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);E7(this,new z7(this.u,b,this.D))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.lG,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Ms,b))};
g.k.mB=function(a){if(!this.ha()){C7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)C7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),E7(this,new y7(this.u,b),!0);else{this.ac("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=j6(this.u.ie(),c.label);d&&e6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(C7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Le(this.o),this.o=new y7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.oB,this,this.o)),this.o.jk(null));this.o.Qu(a)}}};
g.k.mP=function(){return this.o?this.o.qD():null};
g.k.RM=function(a){this.ha()||(this.ac("Failed to estabilish a session: "+g.Ok(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&E7(this,null))};
g.k.wM=function(a){C7("Receiver availability updated: "+a);if(!this.ha()){var b=D7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;D7(this)!=b&&this.S("yt-remote-cast2-availability-change",D7(this))}};
g.k.pD=function(){this.ha()||(this.A=Tya(this),C7("Updating custom receivers: "+g.Ok(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ia,(0,g.x)(function(){this.ac("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",D7(this)))};
B7.prototype.setLaunchParams=B7.prototype.qO;B7.prototype.setConnectedScreenStatus=B7.prototype.pO;B7.prototype.stopSession=B7.prototype.nP;B7.prototype.getCastSession=B7.prototype.mP;B7.prototype.requestSession=B7.prototype.requestSession;B7.prototype.init=B7.prototype.init;B7.prototype.dispose=B7.prototype.dispose;var K7=[];g.k=P7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";Q7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Gf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.D=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.fb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.H+R7(this):this.H};
g.k.clone=function(){return new P7(V7(this))};g.r(X7,g.N);g.k=X7.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ia,c8(this,"play")):b8(this,"play"),a8(this,1,T7(Y7(this))),this.S("remotePlayerChange")):Z7(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ia,c8(this,"pause")):b8(this,"pause"),a8(this,2,T7(Y7(this))),this.S("remotePlayerChange")):Z7(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=Y7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.fb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ia,c8(this,"seekTo",{newTime:a}))}else b8(this,"seekTo",{newTime:a});a8(this,3,a);this.S("remotePlayerChange")}else Z7(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ia,c8(this,"stopVideo")):b8(this,"stopVideo");var a=Y7(this);a.index=-1;a.videoId="";Q7(a);$7(this,a);this.S("remotePlayerChange")}else Z7(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=Y7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){g7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){g7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);b8(this,"setVolume",e)}c.muted=b;c.volume=a;$7(this,c)}else Z7(this,g.Qa(this.setVolume,a,b))};
g.k.lD=function(a,b){if(1==this.o){var c=Y7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ok(b.style),g.Ub(d,c.o));b8(this,"setSubtitlesTrack",d);$7(this,c)}else Z7(this,g.Qa(this.lD,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();b8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=Y7(this);d.audioTrackId=c;$7(this,d)}else Z7(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=Y7(this);c=c||0;var m={videoId:a,currentIndex:c};U7(l,a,c);void 0!==b&&(S7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Ok(h));b8(this,"setPlaylist",m);d||$7(this,l)};
g.k.Vp=function(a,b){if(1==this.o){if(a&&b){var c=Y7(this);U7(c,a,b);$7(this,c)}b8(this,"previous")}else Z7(this,g.Qa(this.Vp,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=Y7(this);U7(c,a,b);$7(this,c)}b8(this,"next")}else Z7(this,g.Qa(this.nextVideo,a,b))};
g.k.hx=function(){1==this.o?b8(this,"dismissAutoplay"):Z7(this,this.hx)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.Z=function(){fza(this);this.B=null;this.C.clear();W7(this,null);g.N.prototype.Z.call(this)};
g.k.Dv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.db(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.pM=function(a,b){this.S(a,b)};
g.k.yK=function(a){if(!a)this.Cm(null),W7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=Y7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)g7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,$7(this,b)}};
g.k.Cm=function(a){g7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.H);if(this.u=a)this.u.addUpdateListener(this.H),gza(this),this.S("remotePlayerChange")};
g.k.xK=function(a){a?(gza(this),this.S("remotePlayerChange")):this.Cm(null)};
g.k.ev=function(){b8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.IK=function(){var a=cza();a&&W7(this,a)};
g.k.ac=function(a){g7("CP",a)};g.r(d8,g.N);g.k=d8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Xa.listId=c);this.Xa.videoId=d;this.Xa.index=h||0;this.Xa.state=3;S7(this.Xa,m);this.B="UNSUPPORTED";e8("Connecting with setPlaylist and params: "+g.Ok(l));this.o.connect({method:"setPlaylist",
params:g.Ok(l)},a,txa())}else e8("Connecting without params"),this.o.connect({},a,txa());iza(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),f8(this,3));g.N.prototype.dispose.call(this)};
g.k.Z=function(){g8(this);i8(this);h8(this);g.Oo(this.G);this.G=NaN;g.Oo(this.H);this.H=NaN;this.A=null;g.jp(this.T);this.T.length=0;this.o.dispose();g.N.prototype.Z.call(this);this.B=this.D=this.u=this.Xa=this.o=null};
g.k.BF=function(){this.Lj(2)};
g.k.CK=function(){e8("Channel opened");this.N&&(this.N=!1,h8(this),this.R=g.Mo((0,g.x)(function(){e8("Timing out waiting for a screen.");this.Lj(1)},this),15E3));
xxa(sya(this.o),this.V)};
g.k.zK=function(){e8("Channel closed");isNaN(this.C)?o6(!0):o6();this.dispose()};
g.k.AK=function(a){o6();isNaN(this.Pl())?(e8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,e8("Channel error: "+a+" with reconnection in "+this.Pl()+" ms"),f8(this,2))};
g.k.BK=function(a){a.params?e8("Received: action="+a.action+", params="+g.Ok(a.params)):e8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=v6(a.params.devices);this.u=(0,g.Hc)(a,function(c){return new c6(c)});
a=!!g.Za(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
lza(this,a);break;case "loungeScreenDisconnected":g.ib(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
lza(this,!1);break;case "remoteConnected":var b=new c6(v6(a.params.device));g.Za(this.u,function(c){return b?c.id==b.id:!1})||dxa(this.u,b);
break;case "remoteDisconnected":b=new c6(v6(a.params.device));g.ib(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":nza(this,a);break;case "nowPlaying":pza(this,a);break;case "onStateChange":oza(this,a);break;case "onAdStateChange":qza(this,a);break;case "onVolumeChanged":rza(this,a);break;case "onSubtitlesTrackChanged":mza(this,a);break;case "nowAutoplaying":sza(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.S("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":tza(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:e8("Unrecognized action: "+a.action)}};
g.k.dO=function(){if(this.A){var a=this.A;this.A=null;this.Xa.videoId!=a&&j8(this,"getNowPlaying")}};
g.k.sF=function(){var a=3;this.ha()||(a=0,isNaN(this.Pl())?b7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Lj=function(a){e8("Disconnecting with "+a);g8(this);this.S("beforeDisconnect",a);1==a&&o6();tya(this.o,a);this.dispose()};
g.k.rF=function(){var a=this.Xa;this.A&&(a=this.Xa.clone(),U7(a,this.A,a.index));return V7(a)};
g.k.rO=function(a){var b=new P7(a);b.videoId&&b.videoId!=this.Xa.videoId&&(this.A=b.videoId,g.Oo(this.G),this.G=g.Mo((0,g.x)(this.dO,this),5E3));var c=[];this.Xa.listId==b.listId&&this.Xa.videoId==b.videoId&&this.Xa.index==b.index||c.push("remoteQueueChange");this.Xa.playerState==b.playerState&&this.Xa.volume==b.volume&&this.Xa.muted==b.muted&&T7(this.Xa)==T7(b)&&g.Ok(this.Xa.o)==g.Ok(b.o)||c.push("remotePlayerChange");this.Xa.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.Tx=function(){var a=this.o.D.id,b=g.Za(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Pl=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.C)():NaN};
g.k.gF=function(){return this.B||"UNSUPPORTED"};
g.k.hF=function(){return this.D||""};
g.k.fP=function(){if(!isNaN(this.Pl())){var a=this.o.u;g.zn(a.o);a.start()}};
g.k.lO=function(a,b){j8(this,a,b);kza(this)};
d8.prototype.subscribe=d8.prototype.subscribe;d8.prototype.unsubscribeByKey=d8.prototype.Qh;d8.prototype.getProxyState=d8.prototype.sF;d8.prototype.disconnect=d8.prototype.Lj;d8.prototype.getPlayerContextData=d8.prototype.rF;d8.prototype.setPlayerContextData=d8.prototype.rO;d8.prototype.getOtherConnectedRemoteId=d8.prototype.Tx;d8.prototype.getReconnectTimeout=d8.prototype.Pl;d8.prototype.getAutoplayMode=d8.prototype.gF;d8.prototype.getAutoplayVideoId=d8.prototype.hF;d8.prototype.reconnect=d8.prototype.fP;
d8.prototype.sendMessage=d8.prototype.lO;g.r(k8,k7);g.k=k8.prototype;g.k.ie=function(a){return this.Ed.$_gs(a)};
g.k.contains=function(a){return!!this.Ed.$_c(a)};
g.k.get=function(a){return this.Ed.$_g(a)};
g.k.start=function(){this.Ed.$_st()};
g.k.add=function(a,b,c){this.Ed.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ed.$_r(a,b,c)};
g.k.Eq=function(a,b,c,d){this.Ed.$_un(a,b,c,d)};
g.k.Z=function(){for(var a=0,b=this.o.length;a<b;++a)this.Ed.$_ubk(this.o[a]);this.o.length=0;this.Ed=null;k7.prototype.Z.call(this)};
g.k.jP=function(){this.S("screenChange")};
g.k.TL=function(){this.S("onlineScreenChange")};
t7.prototype.$_st=t7.prototype.start;t7.prototype.$_gspc=t7.prototype.kP;t7.prototype.$_gsppc=t7.prototype.oD;t7.prototype.$_c=t7.prototype.contains;t7.prototype.$_g=t7.prototype.get;t7.prototype.$_a=t7.prototype.add;t7.prototype.$_un=t7.prototype.Eq;t7.prototype.$_r=t7.prototype.remove;t7.prototype.$_gs=t7.prototype.ie;t7.prototype.$_gos=t7.prototype.nD;t7.prototype.$_s=t7.prototype.subscribe;t7.prototype.$_ubk=t7.prototype.Qh;var D8=null,C8=!1,l8=null,m8=null,B8=null,q8=[];g.r(E8,g.z);g.k=E8.prototype;g.k.Z=function(){g.z.prototype.Z.call(this);this.o.stop();this.u.stop();this.G.stop();this.R();var a=this.Ra;a.unsubscribe("proxyStateChange",this.iB,this);a.unsubscribe("remotePlayerChange",this.Gm,this);a.unsubscribe("remoteQueueChange",this.Qp,this);a.unsubscribe("previousNextChange",this.eB,this);a.unsubscribe("nowAutoplaying",this.aB,this);a.unsubscribe("autoplayDismissed",this.yA,this);this.Ra=this.module=null};
g.k.vz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ra.o)if(G8(this)){if(!Y7(this.Ra).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Y7(this.Ra).fb()?this.Ra.pause():this.Ra.play();break;case "control_play":this.Ra.play();break;case "control_pause":this.Ra.pause();break;case "control_seek":this.D.Zy(c[0],c[1]);break;case "control_subtitles_set_track":H8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.K.getCurrentTime();I8(this,0===c?void 0:c);break;case "control_seek":I8(this,c[0]);break;case "control_subtitles_set_track":H8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.wK=function(a){this.G.yF(a)};
g.k.MO=function(a){this.vz("control_subtitles_set_track",g.Ob(a)?null:a)};
g.k.wC=function(){var a=this.K.getOption("captions","track");g.Ob(a)||H8(this,a)};
g.k.Ub=function(a){this.module.Ub(a,this.K.getVideoData().lengthSeconds)};
g.k.OA=function(a){if(G8(this)){this.Ra.unsubscribe("remotePlayerChange",this.Gm,this);var b=Math.round(a.volume);a=!!a.muted;var c=Y7(this.Ra);if(b!==c.volume||a!==c.muted)this.Ra.setVolume(b,a),this.H.start();this.Ra.subscribe("remotePlayerChange",this.Gm,this)}};
g.k.tL=function(){g.Ob(this.A)||Fza(this,this.A);this.B=!1};
g.k.iB=function(a,b){this.u.stop();2===b&&this.vC()};
g.k.Gm=function(){if(G8(this)){this.o.stop();var a=Y7(this.Ra);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.Vc=1;break;case 1082:case 1083:this.module.Vc=0;break;default:this.module.Vc=-1}switch(a.playerState){case 1081:case 1:F8(this,new g.FC(8));this.uC();break;case 1085:case 3:F8(this,new g.FC(9));break;case 1083:case 0:F8(this,new g.FC(2));this.D.stop();this.Ub(this.K.getVideoData().lengthSeconds);break;case 1084:F8(this,new g.FC(4));break;case 2:F8(this,new g.FC(4));
this.Ub(T7(a));break;case -1:F8(this,new g.FC(64));break;case -1E3:F8(this,new g.FC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=Y7(this.Ra).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,Fza(this,a));a=Y7(this.Ra);-1===a.volume||Math.round(this.K.getVolume())===a.volume&&this.K.isMuted()===a.muted||this.H.isActive()||this.ZC()}else Eza(this)};
g.k.eB=function(){this.K.S("mdxpreviousnextchange")};
g.k.Qp=function(){G8(this)||Eza(this)};
g.k.aB=function(a){isNaN(a)||this.K.S("mdxnowautoplaying",a)};
g.k.yA=function(){this.K.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){G8(this)&&this.Ra.setAudioTrack(this.K.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===Y7(this.Ra).playerState?I8(this,a):b&&this.Ra.seekTo(a)};
g.k.ZC=function(){if(G8(this)){var a=Y7(this.Ra);this.events.eb(this.J);a.muted?this.K.mute():this.K.unMute();this.K.setVolume(a.volume);this.J=this.events.M(this.K,"onVolumeChange",this.OA)}};
g.k.uC=function(){this.o.stop();if(!this.Ra.ha()){var a=Y7(this.Ra);a.fb()&&F8(this,new g.FC(8));this.Ub(T7(a));this.o.start()}};
g.k.vC=function(){this.u.stop();this.o.stop();var a=this.Ra.B.getReconnectTimeout();2==this.Ra.o&&!isNaN(a)&&this.u.start()};g.r(J8,g.Q);J8.prototype.Wb=function(){this.u.show()};
J8.prototype.A=function(){g.RN("https://support.google.com/youtube/answer/7640706")};
J8.prototype.B=function(){b6("mdx-manual-pairing-popup-ok");this.u.hide()};g.r(K8,g.Q);K8.prototype.Wb=function(){this.u.show()};
K8.prototype.A=function(){b6("mdx-privacy-popup-cancel");this.u.hide()};
K8.prototype.B=function(){b6("mdx-privacy-popup-confirm");this.u.hide()};g.r(L8,g.Q);L8.prototype.A=function(a){Hza(this,a.state)};g.r(M8,g.rP);M8.prototype.D=function(){var a=this.K.getOption("remote","receivers");a&&1<a.length&&!this.K.getOption("remote","quickCast")?(this.Yh=g.xb(a,this.A,this),g.tP(this,(0,g.Hc)(a,this.A)),a=this.K.getOption("remote","currentReceiver"),this.Eb(this.A(a)),this.enable(!0)):this.enable(!1)};
M8.prototype.A=function(a){return a.key};
M8.prototype.kf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Yh[a].name};
M8.prototype.od=function(a){g.rP.prototype.od.call(this,a);this.K.setOption("remote","currentReceiver",this.Yh[a]);this.u.kb()};g.r(N8,g.OL);g.k=N8.prototype;
g.k.create=function(){yza(g.Ny(this.player.O()));this.subscriptions.push(g.To("yt-remote-before-disconnect",this.uK,this));this.subscriptions.push(g.To("yt-remote-connection-change",this.xM,this));this.subscriptions.push(g.To("yt-remote-receiver-availability-change",this.gB,this));this.subscriptions.push(g.To("yt-remote-auto-connect",this.vM,this));this.subscriptions.push(g.To("yt-remote-receiver-resumed",this.uM,this));this.subscriptions.push(g.To("mdx-privacy-popup-confirm",this.RN,this));this.subscriptions.push(g.To("mdx-privacy-popup-cancel",
this.QN,this));this.subscriptions.push(g.To("mdx-manual-pairing-popup-ok",this.GG,this));this.gB()};
g.k.load=function(){this.player.cancelPlayback();g.OL.prototype.load.call(this);this.ce=new E8(this,this.player,this.Ra);var a=(a=Dza())?a.currentTime:0;var b=A8()?new X7(v8(),void 0):null;0==a&&b&&(a=T7(Y7(b)));0!==a&&this.Ub(a);Gza(this,this.Kb,this.Kb);g.mT(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.jh=this.hf;g.Me(this.ce,this.Ra);this.Ra=this.ce=null;g.OL.prototype.unload.call(this);g.mT(this.player.app,5);O8(this)};
g.k.Z=function(){g.Uo(this.subscriptions);g.OL.prototype.Z.call(this)};
g.k.Rf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.ce.vz.apply(this.ce,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Vc};
g.k.uF=function(){return this.loaded?this.ce.suggestion:null};
g.k.Gf=function(){return this.Ra?Y7(this.Ra).Gf:!1};
g.k.hasNext=function(){return this.Ra?Y7(this.Ra).hasNext:!1};
g.k.Ub=function(a,b){this.Ky=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.Ky};
g.k.getProgressState=function(){var a=Y7(this.Ra),b=this.player.getVideoData();return{allowSeeking:g.O(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Uc():!a.isAdPlaying()&&this.player.Uc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+R7(a):a.B,isAtLiveHead:1>=(a.A?a.u+R7(a):a.u)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.A?a.u+R7(a):a.u,seekableStart:0<a.C?a.C+
R7(a):a.C}};
g.k.nextVideo=function(){this.Ra&&this.Ra.nextVideo()};
g.k.Vp=function(){this.Ra&&this.Ra.Vp()};
g.k.uK=function(a){1===a&&(this.tu=this.Ra?Y7(this.Ra):null)};
g.k.xM=function(){var a=A8()?new X7(v8(),void 0):null;if(a){var b=this.jh;this.loaded&&this.unload();this.Ra=a;this.tu=null;b.key!==this.hf.key&&(this.jh=b,this.load())}else g.Le(this.Ra),this.Ra=null,this.loaded&&(this.unload(),(a=this.tu)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,T7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.gB=function(){this.Yh=[this.hf].concat(Aza());var a=w8()||this.hf;P8(this,a);this.player.ra("onMdxReceiversChange")};
g.k.vM=function(){var a=w8();P8(this,a)};
g.k.uM=function(){this.jh=w8()};
g.k.RN=function(){this.Hm=!0;O8(this);C8=!1;D8&&y8(D8,1);D8=null};
g.k.QN=function(){this.Hm=!1;O8(this);P8(this,this.hf);this.jh=this.hf;C8=!1;D8=null;this.player.playVideo()};
g.k.GG=function(){this.Wo=!0;O8(this);g.vs("yt-remote-manual-pairing-warning-shown",!0,2592E3);C8=!1;D8&&y8(D8,1);D8=null};
g.k.Sc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Yh;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?N7():P8(this,b)),this.loaded?this.jh:this.hf;case "quickCast":return 2===this.Yh.length&&"cast-selector-receiver"===this.Yh[1].key?(b&&N7(),!0):!1}};
g.k.ev=function(){this.Ra.ev()};
g.k.rf=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.cM.remote=N8;})(_yt_player);
