(function(g){var window=this;var $va=function(a,b){a.ra("onAutonavCoundownStarted",b)},O4=function(a,b,c){var d=b.Ca();
g.J(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.xc(c?c:"mqdefault.jpg");var f=b instanceof g.YA&&b.lengthSeconds?g.AM(b.lengthSeconds):null,h=!!e;e=h&&"RD"===(new g.kC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.YA?b.xa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.vl||g.zM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.uh(),is_live:l,is_list:h,is_mix:e,background:c?"background-image: url("+
c+")":""};b instanceof g.lC&&(d.playlist_length=b.getLength());a.update(d)},P4=function(a,b){g.Q.call(this,{F:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},R4=function(a){g.Q.call(this,{F:"div",
Y:["ytp-upnext","ytp-player-content"],P:{"aria-label":"{{aria_label}}"},L:[{F:"div",I:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{F:"span",I:"ytp-upnext-top",L:[{F:"span",I:"ytp-upnext-header",X:"Up Next"},{F:"span",I:"ytp-upnext-title",X:"{{title}}"},{F:"span",I:"ytp-upnext-author",X:"{{author}}"}]},{F:"a",I:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Play next video"},L:[{F:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},L:[{F:"circle",
I:"ytp-svg-autoplay-circle",P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",I:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",I:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",I:"ytp-upnext-bottom",L:[{F:"span",I:"ytp-upnext-cancel"},{F:"span",I:"ytp-upnext-paused",X:"Autoplay is paused"}]}]});
this.api=a;this.cancelButton=null;this.D=this.o["ytp-svg-autoplay-ring"];this.A=this.notification=this.u=this.suggestion=null;this.B=new g.H(this.Qn,5E3,this);this.C=0;var b=this.o["ytp-upnext-cancel"];this.cancelButton=new g.Q({F:"button",Y:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancel autoplay"},X:"Cancel"});g.A(this,this.cancelButton);this.cancelButton.na("click",this.qI,this);this.cancelButton.da(b);g.A(this,this.B);g.EL(this.api,this.element,this,18788);this.M(this.o["ytp-upnext-autoplay-icon"],
"click",this.ZL);this.xA();this.M(a,"autonavvisibility",this.xA);this.M(a,"mdxnowautoplaying",this.uL);this.M(a,"mdxautoplaycanceled",this.vL);this.M(a,"mdxautoplayupnext",this.XC);Q4(this)&&(a=(a=g.kL(g.dL(this.api)))?a.uF():null)&&this.XC(a);g.J(this.element,"ytp-upnext-mobile",this.api.O().o)},T4=function(a,b){a.u||(g.Vo("a11y-announce","Up Next "+a.suggestion.title),a.C=(0,g.M)(),a.u=new g.H(function(){S4(a,b)},25),S4(a,b),$va(a.api,b||g.P(a.api.O().experiments,"autoplay_time")||1E4));
g.In(a.element,"ytp-upnext-autoplay-paused")},Q4=function(a){return 3===a.api.getPresentingPlayerType()},S4=function(a,b){var c=b||g.P(a.api.O().experiments,"autoplay_time")||1E4,d=Math.min(awa(a),c);
c=Math.min(d/c,1);a.D.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&!Q4(a)?a.select(!0):a.u&&a.u.start()},awa=function(a){return(0,g.M)()-a.C},V4=function(a){U4(a);
a.C=(0,g.M)();S4(a);g.I(a.element,"ytp-upnext-autoplay-paused")},U4=function(a){a.u&&(a.u.dispose(),a.u=null)},bwa=function(a){P4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.Q({F:"div",I:"ytp-subscribe-card",L:[{F:"img",I:"ytp-author-image",P:{src:b.Wd}},{F:"div",I:"ytp-subscribe-card-right",L:[{F:"div",I:"ytp-author-name",X:b.author},{F:"div",I:"html5-subscribe-button-container"}]}]});g.A(this,this.u);this.u.da(this.element);this.subscribeButton=new g.fR("Subscribe",null,"Unsubscribe",null,!0,!1,b.Wg,b.subscribed,"trailer-endscreen",null,null,a);g.A(this,this.subscribeButton);this.subscribeButton.da(this.u.o["html5-subscribe-button-container"]);
this.hide()},W4=function(a){var b=a.O(),c=g.rt||g.Ah?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.Q.call(this,{F:"a",Y:e,P:{href:"{{url}}",target:d?b.D:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{F:"div",I:"ytp-videowall-still-image",P:{style:"{{background}}"}},{F:"span",I:"ytp-videowall-still-info",L:[{F:"span",I:"ytp-videowall-still-info-bg",L:[{F:"span",I:"ytp-videowall-still-info-content",P:c,L:[{F:"span",I:"ytp-videowall-still-info-title",X:"{{title}}"},{F:"span",I:"ytp-videowall-still-info-author",
X:"{{author_and_views}}"},{F:"span",I:"ytp-videowall-still-info-live",X:"Live"},{F:"span",I:"ytp-videowall-still-info-duration",X:"{{duration}}"}]}]}]},{F:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",I:"ytp-videowall-still-listlabel-length",L:[" (",{F:"span",X:"{{playlist_length}}"},")"]}]},{F:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{F:"span",I:"ytp-videowall-still-listlabel-length",X:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.A=new g.zr(this);g.A(this,this.A);this.na("click",this.onClick);this.na("keypress",this.C);this.A.M(a,"videodatachange",this.B);g.FL(a,this.element,this);this.B()},X4=function(a){P4.call(this,a,"videowall-endscreen");
var b=this;this.K=a;this.B=0;this.stills=[];this.C=this.videoData=this.suggestions=null;this.D=this.J=!1;this.H=null;this.A=new g.KQ(this);g.A(this,this.A);this.G=new g.H(function(){g.I(b.element,"ytp-show-tiles")},0);
g.A(this,this.G);var c=new g.Q({F:"button",Y:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Previous"},L:[g.UM()]});g.A(this,c);c.da(this.element);c.na("click",this.FH,this);this.table=new g.Fu({F:"div",I:"ytp-endscreen-content"});g.A(this,this.table);this.table.da(this.element);c=new g.Q({F:"button",Y:["ytp-button","ytp-endscreen-next"],P:{"aria-label":"Next"},L:[g.VM()]});g.A(this,c);c.da(this.element);c.na("click",this.EH,this);this.u=new R4(a);g.A(this,this.u);g.CL(this.player,this.u.element,
4);this.hide()},Y4=function(a){return g.DL(a.player)&&a.Bw()&&!a.C},cwa=function(a,b){return(0,g.Hc)(b.suggestions,function(c){c=g.CM(a.K.O(),c);
g.A(a,c);return c})},Z4=function(a){var b=a.Bt();
b!==a.J&&(a.J=b,a.player.S("autonavvisibility"))},$4=function(a){g.OL.call(this,a);
this.endScreen=null;this.listeners=new g.zr(this);g.A(this,this.listeners);this.o=a.O();dwa(a)?this.endScreen=new X4(this.player):this.o.Za?this.endScreen=new bwa(this.player):this.endScreen=new P4(this.player);g.A(this,this.endScreen);g.CL(this.player,this.endScreen.element,4);this.eC();this.listeners.M(a,"videodatachange",this.eC,this);this.listeners.M(a,g.jC("endscreen"),this.Wc,this);this.listeners.M(a,"crx_endscreen",this.Ge,this)},dwa=function(a){a=a.O();
return a.Ba&&!a.Za};
g.r(P4,g.Q);g.k=P4.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Bw=function(){return!1};
g.k.Bt=function(){return!1};
g.k.Gy=function(){return!1};g.r(R4,g.Q);g.k=R4.prototype;g.k.Qn=function(){this.notification&&(this.B.stop(),this.eb(this.A),this.A=null,this.notification.close(),this.notification=null)};
g.k.xA=function(){g.Ju(this,g.eL(this.api));g.IL(this.api,this.element,g.eL(this.api))};
g.k.QL=function(){window.focus();this.Qn()};
g.k.hide=function(){g.Q.prototype.hide.call(this)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.O(this.api.O().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ca(),this.Qn(),this.notification=new Notification("Up Next",{body:b.title,icon:b.xc()}),this.A=this.M(this.notification,"click",this.QL),this.B.start())}U4(this);this.api.nextVideo(!1,a)};
g.k.ZL=function(a){!g.Be(this.cancelButton.element,g.kp(a))&&g.TN(a,this.api)&&this.select()};
g.k.qI=function(){g.gL(this.api,!0)};
g.k.uL=function(a){Q4(this);this.show();T4(this,a)};
g.k.XC=function(a){Q4(this);this.suggestion&&this.suggestion.Ca().videoId===a.Ca().videoId||(this.suggestion=a,O4(this,a,"hqdefault.jpg"))};
g.k.vL=function(){Q4(this);U4(this);this.hide()};
g.k.Z=function(){U4(this);this.Qn();g.Q.prototype.Z.call(this)};g.r(bwa,P4);g.r(W4,g.Q);W4.prototype.select=function(){var a=this.suggestion.Ca().videoId,b=this.suggestion.getPlaylistId();(g.ET(this.api.app,a,this.suggestion.Tb,b,void 0,void 0)||this.api.ia("web_player_endscreen_double_log_fix_killswitch"))&&g.HL(this.api,this.element)};
W4.prototype.onClick=function(a){g.TN(a,this.api,this.u,this.suggestion.Tb||void 0)&&this.select()};
W4.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.pp(a)||(this.select(),g.op(a))}};
W4.prototype.B=function(){var a=this.api.getVideoData(),b=this.api.O();this.u=a.Qb?!1:b.u};g.r(X4,P4);g.k=X4.prototype;g.k.create=function(){P4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=cwa(this,a),this.videoData=a);this.Pg();this.A.M(this.player,"appresize",this.Pg);this.A.M(this.player,"onVideoAreaChange",this.Pg);this.A.M(this.player,"videodatachange",this.GH);this.A.M(this.player,"autonavchange",this.Ct);this.A.M(this.player,"autonavcancel",this.DH);a=this.videoData.autonavState;a!==this.H&&this.Ct(a);this.A.M(this.element,"transitionend",this.iN)};
g.k.destroy=function(){g.Br(this.A);g.Me(this.stills);this.stills=[];this.suggestions=null;P4.prototype.destroy.call(this);g.In(this.element,"ytp-show-tiles");this.G.stop();this.H=this.videoData.autonavState};
g.k.Bw=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){P4.prototype.show.call(this);g.In(this.element,"ytp-show-tiles");this.player.O().o?g.zn(this.G):this.G.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.gL(this.player,!1);Y4(this)?(Z4(this),2===this.videoData.autonavState?this.player.O().ia("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):T4(this.u):3===this.videoData.autonavState&&V4(this.u)):(g.gL(this.player,!0),Z4(this))};
g.k.hide=function(){P4.prototype.hide.call(this);V4(this.u);Z4(this)};
g.k.iN=function(a){g.kp(a)===this.element&&this.Pg()};
g.k.Pg=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=g.tL(this.K,!0,this.K.isFullscreen()),b=g.cC(this.K);b&&(b=b.sc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,w=e<=h-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&w)n-=q*m,e+=2;else if(u)n-=
t*m,b+=2;else if(w)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;c=this.player.O().ia("web_player_no_endscreen_crop")?1:1.21;m*=g.Rd(a.width/m||1,1,c);n*=g.Rd(a.height/n||1,1,c);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Ph(a,m,n);g.xh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.suggestion=f;O4(c,f,"hqdefault.jpg");g.J(this.element,
"ytp-endscreen-takeover",Y4(this));Z4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(q=c,t=0,d&&f>=b-2&&h>=e-2?t=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(t=2):t=2),q=g.Sd(q+this.B,l),0!==t){u=this.stills[c];u||(u=new W4(this.player),this.stills[c]=u,a.appendChild(u.element));w=Math.floor(n*h/e);var B=Math.floor(m*f/b),D=Math.floor(n*(h+t)/e)-w-4,E=Math.floor(m*(f+t)/b)-B-4;g.Fh(u.element,B,w);g.Ph(u.element,E,D);g.xh(u.element,"transitionDelay",(h+f)/20+"s");g.J(u.element,"ytp-videowall-still-mini",
1===t);g.J(u.element,"ytp-videowall-still-large",2<t);t=u;q=this.suggestions[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.O(),w=g.Gn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",O4(t,q,w),g.Hy(u)&&(u=q.uh(),u=g.Cd(u,g.oI({},"emb_rel_end")),t.oa("url",u)),(q=(q=q.Tb)&&q.itct)&&g.GL(t.api,t.element,q));c++}g.J(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ye(e.element),g.Le(e);this.stills.length=c}};
g.k.GH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.suggestions=cwa(this,a),this.videoData=a,this.Pg())};
g.k.EH=function(){this.B+=this.stills.length;this.Pg()};
g.k.FH=function(){this.B-=this.stills.length;this.Pg()};
g.k.Gy=function(){return!!this.u.u};
g.k.Ct=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,U4(this.u),this.Ja()&&this.Pg()):(this.D=!0,this.Ja()&&Y4(this)&&(2===a?T4(this.u):3===a&&V4(this.u)))};
g.k.DH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.IL(this.K,this.stills[a].element,!0);this.Ct(1)}else this.C=null,this.D=!1;this.Pg()};
g.k.Bt=function(){return this.Ja()&&Y4(this)};g.r($4,g.OL);g.k=$4.prototype;g.k.fz=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!dwa(this.player)||b;var c=a.zj||g.Qy(a.Sa),d=g.YS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.ez=function(){return this.endScreen.Bt()};
g.k.oG=function(){return this.ez()?this.endScreen.Gy():!1};
g.k.Z=function(){g.BR(this.player.app,"endscreen",void 0);g.OL.prototype.Z.call(this)};
g.k.load=function(){g.OL.prototype.load.call(this);this.endScreen.show()};
g.k.unload=function(){g.OL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Wc=function(a){this.fz()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.Ge=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.eC=function(){g.BR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.gC(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.gC(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.yL(this.player,[a,b])};g.cM.endscreen=$4;})(_yt_player);
